name = "DistributedMonteCarlo"
uuid = "1911db96-88a4-4c72-b932-f455b4e9470b"
authors = ["Maximilian Bittens <maximilian.bittens@bgr.de>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"
